# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"D\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"\"\n\x12GetProductsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\"6\n\x13GetProductsResponse\x12\x1f\n\x08products\x18\x01 \x03(\x0b\x32\r.product.Item\"$\n\x16GetProductsByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"9\n\x17GetProductsByIdResponse\x12\x1e\n\x07product\x18\x01 \x01(\x0b\x32\r.product.Item2\xad\x01\n\x07Product\x12J\n\x0bGetProducts\x12\x1b.product.GetProductsRequest\x1a\x1c.product.GetProductsResponse\"\x00\x12V\n\x0fGetProductsById\x12\x1f.product.GetProductsByIdRequest\x1a .product.GetProductsByIdResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=26
  _globals['_ITEM']._serialized_end=94
  _globals['_GETPRODUCTSREQUEST']._serialized_start=96
  _globals['_GETPRODUCTSREQUEST']._serialized_end=130
  _globals['_GETPRODUCTSRESPONSE']._serialized_start=132
  _globals['_GETPRODUCTSRESPONSE']._serialized_end=186
  _globals['_GETPRODUCTSBYIDREQUEST']._serialized_start=188
  _globals['_GETPRODUCTSBYIDREQUEST']._serialized_end=224
  _globals['_GETPRODUCTSBYIDRESPONSE']._serialized_start=226
  _globals['_GETPRODUCTSBYIDRESPONSE']._serialized_end=283
  _globals['_PRODUCT']._serialized_start=286
  _globals['_PRODUCT']._serialized_end=459
# @@protoc_insertion_point(module_scope)
